[[language]]
name = "rust"
auto-format = false

[[language]]
name = "lua"
auto-format = false

[[language]]
name = "bash"
auto-format = false
file-types = [
  ".aliases", 
  ".zshrc", 
  "zshrc", 
  ".zprofile", 
  "zshenv", 
  ".zshenv", 
  "zprofile", 
  "conf", 
  "zsh"
]

[[language]]
name = "python"
auto-format = false

[[language]]
name = "html"
auto-format = false

[[language]]
name = "css"
auto-format = false

[[language]]
name = "yaml"
auto-format = false

[[language]]
name = "toml"
auto-format = false
