# Soft Nord Theme (dark) for Helix Text Editor

"attribute" = "nord7"
"keyword" = { fg = "nord10" }
"keyword.directive" = "nord15"
"namespace" = "nord7"
"punctuation" = "nord4"
"punctuation.delimiter" = "nord4"
"operator" = "nord15"
"special" = "nord15"
"variable" = "nord6"
"variable.builtin" = "nord4"
"variable.parameter" = "nord7"
"variable.other.member" = "nord9"
"type" = "nord15"
"type.builtin" = "nord15"
"constructor" = { fg = "nord8", modifiers = ["italic"] }
"function" = { fg = "nord8", modifiers = ["italic"] }
"function.macro" = "nord7"
"function.builtin" = "nord8"
"tag" = "nord8"
"comment" = { fg = "nord9", modifiers = ["italic", "dim"] }
"constant" = { fg = "nord15" }
"constant.builtin" = { fg = "nord15", modifiers = ["bold"] }
"string" = {fg = "nord14", modifiers = ["italic"] }
"constant.numeric" = "nord15"
"constant.character.escape" = { fg = "nord5", modifiers = ["bold"] }
"label" = "nord8"
"module" = "nord8"

"diff.plus" = "nord14"
"diff.delta" = "nord12"
"diff.minus" = "nord11"

"warning" = "nord12"
"error" = "nord11"
"info" = "nord7"
"hint" = "nord9"
"diagnostic" = { bg = "nord1" }

"ui.background" = {}

# Number Lines
"ui.linenr" = { fg = "nord3" }
"ui.linenr.selected" = { fg = "nord8", modifiers = ["bold"] }

# Cursor
"ui.cursor.primary" = { fg = "nord0", bg = "nord4" }
"ui.cursor.match" = { fg = "nord4", bg = "nord3" }
"ui.cursorline.primary" = { bg = "nord1" }
"ui.cursorline.secondary" = { bg = "nord1" }
"ui.cursorcolumn.primary" = { bg = "nord1" }
"ui.cursorcolumn.secondary" = { bg = "nord1" }

# Selections
"ui.selection.primary" = { fg = "nord0", bg = "nord6" }
"ui.selection" = { fg = "nord1", bg = "nord4" }

# Statusline
"ui.statusline" = { fg = "nord4", bg = "nord0" }
"ui.statusline.inactive" = { fg = "nord3" }
"ui.statusline.normal" = { fg = "nord14"}
"ui.statusline.insert" = { fg = "nord13"}
"ui.statusline.select" = { fg = "nord15"}
"ui.statusline.separator" = "nord1"

"ui.popup" = { bg = "nord1" }
"ui.window" = { bg = "nord1" }
"ui.help" = { bg = "nord1", fg = "nord4" }
"ui.text" = { fg = "nord4" }
"ui.text.focus" = { fg = "nord4" }
"ui.menu" = { fg = "nord4", bg = "nord1" }
"ui.menu.selected" = { fg = "nord6", bg = "nord3" }
"ui.virtual.whitespace" = "nord3"
"ui.virtual.ruler" = { bg = "nord3" }

"diagnostic.warning" = { underline = { color = "nord12", style = "curl" } }
"diagnostic.error" = { underline = { color = "nord11", style = "curl" } }
"diagnostic.info" = { underline = { color = "nord7", style = "curl" } }
"diagnostic.hint" = { underline = { color = "nord10", style = "curl" } }

"markup.heading" = "nord7"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "nord14", modifiers = ["underlined"] }
"markup.link.text" = "nord11"
"markup.raw" = "nord11"

[palette]
# Polar Night - Backgrounds
nord0 = "#2e3440"
nord1 = "#3b4252"
nord2 = "#434c5e"
nord3 = "#4c566a"

# Snow Storm - Foregrounds
nord4 = "#d8dee9"
nord5 = "#e5e9f0"
nord6 = "#eceff4"

# Frost - Blue tones
nord7 = "#8fbcbb" # Aqua 1
nord8 = "#88c0d0" # Aqua 2
nord9 = "#81a1c1" # Blue 1
nord10 = "#5e81ac" # Blue 2

# Aurora - Other Colors
nord11 = "#bf616a" # Red
nord12 = "#d08770" # Orange
nord13 = "#ebcb8b" # Yellow
nord14 = "#a3be8c" # Green
nord15 = "#b48ead" # Purple
